import express from 'express';
import {createServer} from 'node:http';
import {Server} from 'socket.io';
import crypto from 'node:crypto';
const app=express(); const http=createServer(app); const io=new Server(http,{cors:{origin:false}});
app.use(express.static('public'));
app.get('/health',(_,res)=>res.json({ok:true}));
const rooms=new Map(), letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ';
const clean=s=>String(s??'').trim().replace(/\s+/g,' ').slice(0,70);
const norm=s=>clean(s).toLocaleLowerCase();
function safeRoom(room,seat){return {code:room.code,seat,phase:room.phase,players:room.players.map(p=>p&&({name:p.name,category:p.category,score:p.score,skips:p.skips,connected:p.connected})),category:room.category,turn:room.turn,letter:room.letter,listLength:room.list.length,finalDone:room.finalDone,finalTurn:room.finalTurn,notice:room.notice,champion:room.champion,pending:room.pending&&{type:room.pending.type||'judge',seat:room.pending.seat,answer:room.pending.answer||''},history:room.history.slice(-8)};}
function broadcast(room){for(let i=0;i<2;i++){const p=room.players[i];if(p?.socket)io.to(p.socket).emit('state',safeRoom(room,i));}}
function error(socket,message){socket.emit('gameError',message)}
function active(room,seat){return room.phase==='playing'&&room.turn===seat}
function advance(room){room.letter++;room.turn=1-room.turn;if(room.letter>=26){room.phase='final';room.finalTurn=0;room.notice='Final memory challenge: +5 for a perfect recall.'}}
function complete(room){room.phase='finished';const [a,b]=room.players;room.champion=a.score===b.score?'Tie game!':a.score>b.score?a.name:b.name;room.notice='Game complete!'}
function join(socket,{code,name,token}){code=clean(code).toUpperCase();name=clean(name).slice(0,22);if(!/^[A-Z0-9]{6}$/.test(code)||!name)return error(socket,'Enter a valid room code and name.');const room=rooms.get(code);if(!room)return error(socket,'Room not found. Ask your friend for a fresh link.');let seat=room.players.findIndex(p=>p?.token===token&&token);if(seat<0){seat=room.players.findIndex(p=>!p);if(seat<0)return error(socket,'This room already has two players.');token=crypto.randomBytes(18).toString('hex');room.players[seat]={name,token,category:'',score:0,skips:0,connected:true,socket:socket.id};}else{room.players[seat].connected=true;room.players[seat].socket=socket.id;}socket.join(code);socket.data={code,seat};socket.emit('identity',{code,token,seat});broadcast(room)}
io.on('connection',socket=>{
 socket.on('create',({name}={})=>{let code;do{code=crypto.randomBytes(4).toString('hex').slice(0,6).toUpperCase()}while(rooms.has(code));rooms.set(code,{code,players:[null,null],phase:'lobby',category:'',turn:0,letter:0,list:[],finalDone:[false,false],finalTurn:0,notice:'Invite your second player.',champion:'',history:[],pending:null,created:Date.now()});join(socket,{code,name});});
 socket.on('join',data=>join(socket,data||{}));
 socket.on('category',({category}={})=>{const {code,seat}=socket.data||{},r=rooms.get(code);if(!r||r.phase!=='lobby'||!r.players[seat])return;const c=clean(category).slice(0,35);if(!c)return error(socket,'Choose a category.');r.players[seat].category=c;r.notice='Both players choose a category, then start.';broadcast(r)});
 socket.on('start',()=>{const {code,seat}=socket.data||{},r=rooms.get(code);if(!r||r.phase!=='lobby'||!r.players.every(p=>p?.category))return error(socket,'Both players must join and choose a category.');const owner=crypto.randomInt(2);r.category=r.players[owner].category;r.turn=1-owner;r.phase='playing';r.notice=`Coin flip selected ${r.players[owner].name}'s category. ${r.players[r.turn].name} starts with A.`;broadcast(r)});
 socket.on('submit',({recall=[],answer}={})=>{const {code,seat}=socket.data||{},r=rooms.get(code);if(!r||!active(r,seat)||r.pending)return;answer=clean(answer);if(!answer||answer[0].toUpperCase()!==letters[r.letter])return error(socket,`New answer must start with ${letters[r.letter]}.`);if(r.list.some(x=>norm(x)===norm(answer)))return error(socket,'That answer has already been used.');if(r.letter>0&&(!Array.isArray(recall)||recall.length!==r.list.length||recall.some((x,i)=>norm(x)!==norm(r.list[i])))){r.players[seat].score--;r.players[seat].skips++;r.history.push(`${r.players[seat].name} missed the recall (−1).`);r.notice='GOTCHA! Recall incorrect. −1 point.';advance(r);broadcast(r);return;}if(r.letter===0){r.list.push(answer);r.players[seat].score++;r.history.push(`${r.players[seat].name} added A.`);r.notice='A accepted. +1 point.';advance(r);broadcast(r);return;}r.pending={seat,answer};r.notice=`${r.players[1-seat].name}: accept or challenge ${answer}?`;broadcast(r)});
 socket.on('judge',({accept}={})=>{const {code,seat}=socket.data||{},r=rooms.get(code);if(!r?.pending||seat===r.pending.seat)return;const {answer,seat:player}=r.pending;r.pending=null;if(accept){r.list.push(answer);r.players[player].score++;r.notice=`${answer} accepted. +1 point.`;}else{r.players[player].score--;r.players[player].skips++;r.notice=`${answer} challenged. −1 point.`;}r.history.push(r.notice);advance(r);broadcast(r)});
 socket.on('eliminate',()=>{const {code,seat}=socket.data||{},r=rooms.get(code);if(!r||!active(r,seat)||r.letter===0||r.pending)return;r.pending={seat,type:'eliminate'};r.notice=`${r.players[1-seat].name}: Can you provide an ${letters[r.letter]} answer?`;broadcast(r)});
 socket.on('prove',({answer,can}={})=>{const {code,seat}=socket.data||{},r=rooms.get(code);if(!r?.pending||r.pending.type!=='eliminate'||seat===r.pending.seat)return;const player=r.pending.seat;if(can){answer=clean(answer);if(!answer||answer[0].toUpperCase()!==letters[r.letter]||r.list.some(x=>norm(x)===norm(answer)))return error(socket,'Provide an unused answer beginning with the current letter.');r.list.push(answer);r.players[player].score--;r.players[player].skips++;r.players[seat].score++;r.notice=`${r.players[seat].name} proved it! +1; opponent −1.`;}else{r.notice='Letter eliminated. No points awarded.';}r.pending=null;r.history.push(r.notice);advance(r);broadcast(r)});
 socket.on('final',({recall=[]}={})=>{const {code,seat}=socket.data||{},r=rooms.get(code);if(!r||r.phase!=='final'||seat!==r.finalTurn||r.finalDone[seat])return;const ok=Array.isArray(recall)&&recall.length===r.list.length&&recall.every((x,i)=>norm(x)===norm(r.list[i]));r.finalDone[seat]=true;if(ok)r.players[seat].score+=5;r.notice=`${r.players[seat].name}: ${ok?'perfect recall, +5!':'recall incomplete, no bonus.'}`;r.history.push(r.notice);if(r.finalDone.every(Boolean))complete(r);else r.finalTurn=1-seat;broadcast(r)});
 socket.on('disconnect',()=>{const {code,seat}=socket.data||{},r=rooms.get(code);if(r?.players[seat]?.socket===socket.id){r.players[seat].connected=false;broadcast(r)}});
});
setInterval(()=>{const now=Date.now();for(const [code,r] of rooms)if(now-r.created>24*60*60*1000)rooms.delete(code)},60*60*1000).unref();
http.listen(process.env.PORT||3000,'0.0.0.0',()=>console.log('AlphaBetchaGotcha running'));
